add: diagram-to-tf-gcs

diff --git a/cloudbuild.yaml b/cloudbuild.yaml
--- a/cloudbuild.yaml
+++ b/cloudbuild.yaml
@@ -1,21 +1,26 @@
 steps:
-- id: 'branch name'
-  name: 'alpine'
-  entrypoint: 'sh'  
-  args: 
-  - '-c'
-  - | 
-      echo "***********************"
-      echo "Branch Name: $BRANCH_NAME"
-      echo "***********************"
-
-- id: 'extract-pr-info'
+- id: 'branch-name'
   name: 'alpine'
   entrypoint: 'sh'
   args:
   - '-c'
   - |
-      # 必要な情報をevent.jsonから抽出
+      echo "***********************"
+      echo "Branch Name: $BRANCH_NAME"
+      echo "***********************"
+
+- id: 'extract-pr-info'
+  name: 'alpine:3.18' # Alpineイメージ
+  entrypoint: 'sh'
+  args:
+  - '-c'
+  - |
+      apk add --no-cache jq
+      if [ ! -f /workspace/event.json ]; then
+          echo "Error: event.json not found."
+          exit 1
+      fi
+
       PR_NUMBER=$(jq '.pull_request.number' /workspace/event.json)
       REPO_NAME=$(jq -r '.repository.name' /workspace/event.json)
       REPO_OWNER=$(jq -r '.repository.owner.login' /workspace/event.json)
@@ -24,41 +29,52 @@ steps:
       echo "REPO_NAME=$REPO_NAME" >> /workspace/env_vars
       echo "REPO_OWNER=$REPO_OWNER" >> /workspace/env_vars
 
-
-- id: 'tf init'
-  name: 'hashicorp/terraform:1.5.6' # 最新安定版のイメージ
+- id: 'tf-init'
+  name: 'hashicorp/terraform:1.5.6'
   entrypoint: 'sh'
-  args: 
+  args:
   - '-c'
   - |
       cd setup
-      terraform init || exit 1
+      terraform init || { echo "Terraform init failed"; exit 1; }
 
-# [START tf-plan]
-- id: 'tf plan'
-  name: 'hashicorp/terraform:1.5.6' # 最新安定版のイメージ
+- id: 'tf-plan'
+  name: 'hashicorp/terraform:1.5.6'
   entrypoint: 'sh'
-  args: 
+  args:
   - '-c'
-  - | 
+  - |
       cd setup
-      terraform plan > plan_output.txt || exit 1
-# [END tf-plan]
+      terraform plan -out=plan_output.txt || { echo "Terraform plan failed"; exit 1; }
 
 - id: 'post-pr-comment'
-  name: 'alpine'
+  name: 'alpine:3.18' # Alpineイメージ
   entrypoint: 'sh'
   env:
     - 'GITHUB_TOKEN=${_GITHUB_TOKEN}'
   args:
   - '-c'
   - |
+      apk add --no-cache jq
+      if [ ! -f /workspace/env_vars ]; then
+          echo "Error: env_vars not found."
+          exit 1
+      fi
+
       source /workspace/env_vars
+      if [ ! -f setup/plan_output.txt ]; then
+          echo "Error: plan_output.txt not found."
+          exit 1
+      fi
+
       COMMENT=$(cat setup/plan_output.txt | jq -Rs .)
       curl -X POST -H "Authorization: Bearer $GITHUB_TOKEN" \
         -H "Content-Type: application/json" \
         -d "{\"body\":${COMMENT}}" \
-        https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/issues/$PR_NUMBER/comments
+        https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/issues/$PR_NUMBER/comments || {
+          echo "Failed to post PR comment."
+          exit 1
+      }
 
 # ログオプションを追加
 options:
